// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
// import Header from "@/components/Header/Header";
// import Footer from "@/components/Footer/Footer";
// import AdminHeader from "@/components/admin/AdminHeader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AdminHeader />
//         {children}
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/admin/AdminSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Scan2Park Admin",
  description: "Admin dashboard for Scan2Park",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen">
          {/* Sidebar takes fixed width on desktop */}
          <AdminSidebar />
          {/* Main content adjusts to sidebar */}
          <main className="flex-1 md:ml-64 p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}